import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, analytics, settings }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50`}
      >
       <div className="flex min-h-screen">
          {/* Main Content */}
          <div className="flex-1 p-6">
            <h1 className="text-3xl font-bold text-gray-900 mb-8">
              Dashboard
            </h1>
            {children}
          </div>

          {/* Parallel Routes Sidebar */}
          <div className="w-130 bg-white border-l border-gray-200">
            <div className="h-1/2 border-b border-gray-200">
              {analytics}
            </div>
            <div className="h-1/2">
              {settings}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
