import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, sidebar }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen bg-gray-50`}
      >

     {/* left column – the parallel slot */}
        <aside className="w-64 border-r bg-white p-4">
          {sidebar}
        </aside>

        {/* right column – main outlet */}
        <main className="flex-1 p-6">{children}</main>
      </body>
    </html>
  );
}
