import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ padding: '1rem', borderBottom: '1px solid #ccc' }}>
          <a href="/login" style={{ marginRight: '1rem' }}>Login</a>
          <a href="/register">Register</a>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
