 "use client"

import { Provider } from 'react-redux';
import { store } from '../store';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { styled } from 'styled-components';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const MainContainer = styled.main`
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
`;


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
          <MainContainer>{children}</MainContainer>
        </Provider>
      </body>
    </html>
  );
}
