import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <header style={{ padding: '20px', background: '#f0f0f0', borderBottom: '1px solid #ccc' }}>
          <h1>My App Header</h1>
          <nav>
            <a href="/" style={{ marginRight: '15px' }}>Home</a>
            <a href="/products" style={{ marginRight: '15px' }}>Products</a>
            <a href="/customers" style={{ marginRight: '15px' }}>Customers</a>
            <a href="/revenue" style={{ marginRight: '15px' }}>Revenue</a>
            <a href="/login" style={{ marginRight: '15px' }}>Login</a>
            {/* <a href="/register">Register</a> */}
          </nav>
        </header>
        <main style={{ padding: '20px', minHeight: '80vh' }}>
          {children}
        </main>

        <footer style={{ padding: '20px', background: '#f0f0f0', borderTop: '1px solid #ccc' }}>
          <p>© 2025 My App Footer</p>
        </footer>
      </body>
    </html>
  );
}
